import elazar from '../../../data/images/try/elazar.png';
import yossi from "../../../data/images/try/yossi.jpeg";
import ofer from "../../../data/images/try/ofer.jpeg";



export const usersColumnsData = [

    {
      id: 1,
      title: "שם",
      col: "main",
      lines: 2,
      value: ["image", "name", "userName"],
      editable: false,
      type: "text",
    },
    {
      id: 2,
      title: "תפקיד",
      col: "titles",
      lines: 2,
      value: ["title", "department"],
      editable: false,
      type: ["text", "text"],
    },
    {
      id: 3,
      title: "פרטים",
      col: "links",
      lines: 2,
      value: ["email", "phone"],
      editable: false,
      type: ["email", "phone"],
    },
    {
      id: 4,
      title: "הרשאה",
      col: "badge",
      value: "role",
      editable: false,
      type: "select",
      option: ["user", "pending", "admin", "dormant"],
      colors: ["green", "lime", "red", "yellow", "purple"]
    },
    {
      id: 6,
      title: "פעולות",
      col: "icon",
      value: "",
      editable: false,
      type: "text",
    },
  ];

  export const usersRowsData = [
    {
      id: 1,
      name: "אלעזר בן חיים",
      userName: "ElazarBenHaim",
      title: "ראש צוות פיתוח",
      department: "צד שרת",
      role: "admin",
      phone: "055-0000000",
      status: "פעיל",
      email: "elazaar@cars.com",
      image: elazar,
    },
    {
      id: 2,
      name: "יוסי סודרי",
      userName: "YossiSoudry",
      title: "אחראי מוצר",
      department: "צד לקוח",
      role: "pending",
      status: "פעיל",
      phone: "055-6686876",
      email: "yossi@cars.com",
      image: yossi,
    },
    {
      id: 3,
      name: "ברקוני המלך",
      userName: "KinkBarkuny",
      title: "עובד חדש",
      department: "לא הוגדר",
      role: "user",
      status: "pending",
      phone: "055-1234567",
      email: "barkuni@example.com",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr5Vvrrjcc96irilOlwpN6zvX7SuJGluLzMQ&usqp=CAU",
    },
    {
      id: 4,
      name: "עופר שלי",
      userName: "OferSheli",
      title: "מרצה פולסטאק",
      department: "לא הוגדר",
      role: "dormant",
      status: "פעיל",
      phone: "055-6666666",
      email: "ofer@example.com",
      image: ofer,
    },
    {
      id: 5,
      name: "אלעזר בן חיים",
      userName: "ElazarBenHaim",
      title: "ראש צוות פיתוח",
      department: "צד שרת",
      role: "admin",
      
      phone: "055-0000000",
      status: "פעיל",
      email: "elazaar@cars.com",
      image: elazar,
    },
    {
      id: 6,
      name: "יוסי סודרי",
      userName: "YossiSoudry",
      title: "אחראי מוצר",
      department: "צד לקוח",
      role: "admin",
      status: "פעיל",
      phone: "055-6686876",
      email: "yossi@cars.com",
      image: yossi,
    },
    {
      id: 7,
      name: "ברקוני המלך",
      userName: "KinkBarkuny",
      title: "עובד חדש",
      department: "לא הוגדר",
      role: "user",
      status: "pending",
      phone: "055-1234567",
      email: "barkuni@example.com",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr5Vvrrjcc96irilOlwpN6zvX7SuJGluLzMQ&usqp=CAU",
    },
    {
      id: 8,
      name: "עופר שלי",
      userName: "OferSheli",
      title: "מרצה פולסטאק",
      department: "לא הוגדר",
      role: "user",
      status: "פעיל",
      phone: "055-6666666",
      email: "ofer@example.com",
      image: ofer,
    },
    {
      id: 9,
      name: "אלעזר בן חיים",
      userName: "ElazarBenHaim",
      title: "ראש צוות פיתוח",
      department: "צד שרת",
      role: "admin",
      
      phone: "055-0000000",
      status: "פעיל",
      email: "elazaar@cars.com",
      image: elazar,
    },
    {
      id: 10,
      name: "יוסי סודרי",
      userName: "YossiSoudry",
      title: "אחראי מוצר",
      department: "צד לקוח",
      role: "admin",
      status: "פעיל",
      phone: "055-6686876",
      email: "yossi@cars.com",
      image: yossi,
    },
    {
      id: 11,
      name: "ברקוני המלך",
      userName: "KinkBarkuny",
      title: "עובד חדש",
      department: "לא הוגדר",
      role: "user",
      status: "pending",
      phone: "055-1234567",
      email: "barkuni@example.com",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr5Vvrrjcc96irilOlwpN6zvX7SuJGluLzMQ&usqp=CAU",
    },
    {
      id: 12,
      name: "עופר שלי",
      userName: "OferSheli",
      title: "מרצה פולסטאק",
      department: "לא הוגדר",
      role: "user",
      status: "פעיל",
      phone: "055-6666666",
      email: "ofer@example.com",
      image: ofer,
    },
    {
      id: 13,
      name: "אלעזר בן חיים",
      userName: "ElazarBenHaim",
      title: "ראש צוות פיתוח",
      department: "צד שרת",
      role: "admin",
      
      phone: "055-0000000",
      status: "פעיל",
      email: "elazaar@cars.com",
      image: elazar,
    },
    {
      id: 14,
      name: "יוסי סודרי",
      userName: "YossiSoudry",
      title: "אחראי מוצר",
      department: "צד לקוח",
      role: "admin",
      status: "פעיל",
      phone: "055-6686876",
      email: "yossi@cars.com",
      image: yossi,
    },
    {
      id: 15,
      name: "ברקוני המלך",
      userName: "KinkBarkuny",
      title: "עובד חדש",
      department: "לא הוגדר",
      role: "user",
      status: "pending",
      phone: "055-1234567",
      email: "barkuni@example.com",
      image:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr5Vvrrjcc96irilOlwpN6zvX7SuJGluLzMQ&usqp=CAU",
    },
    {
      id: 16,
      name: "עופר שלי",
      userName: "OferSheli",
      title: "מרצה פולסטאק",
      department: "לא הוגדר",
      role: "user",
      status: "פעיל",
      phone: "055-6666666",
      email: "ofer@example.com",
      image: ofer,
    },
  ];